<?php

namespace FireFly\FilamentBlog;

use FireFly\FilamentBlog\Components\Card;
use FireFly\FilamentBlog\Components\Comment;
use FireFly\FilamentBlog\Components\FeatureCard;
use FireFly\FilamentBlog\Components\Header;
use FireFly\FilamentBlog\Components\HeaderCategory;
use FireFly\FilamentBlog\Components\Layout;
use FireFly\FilamentBlog\Components\RecentPost;
use Illuminate\Config\Repository as Config;
use Illuminate\Support\Facades\Route;
use Spatie\LaravelPackageTools\Commands\InstallCommand;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class FilamentBlogServiceProvider extends PackageServiceProvider
{
    //    public function register()
    //    {
    //        $this->mergeConfigFrom(__DIR__.'/../config/filamentblog.php', 'filamentblog');
    //    }
    //
    //    public function boot()
    //    {
    //        $this->loadRoutesFrom(__DIR__.'/../routes/web.php');
    //
    //        if ($this->app->runningInConsole()) {
    //            $this->publishes([
    //                __DIR__.'/../config/filamentblog.php' => config_path('filamentblog.php'),
    //            ], 'filamentblog-config');
    //        }
    //
    //    }
    public function configurePackage(Package $package): void
    {

        $this->loadMigrationsFrom(__DIR__.'/../database/migrations');

        $package->name('fire-fly/filament-blog')
            ->hasConfigFile(['filamentblog'])
            ->hasMigration('create_blog_tables')
            ->hasViewComponents(
                'blog',
                Layout::class,
                RecentPost::class,
                Header::class,
                Comment::class,
                HeaderCategory::class,
                FeatureCard::class,
                Card::class
            )
            ->hasViews('filament-blog')
            ->hasRoute('web')
            ->hasInstallCommand(function (InstallCommand $installCommand) {
                $installCommand
                    ->startWith(function (InstallCommand $command) {
                        $command->info('Hello, and welcome to my great new package!');
                    })
                    ->publishConfigFile()
                    ->publishMigrations()
                    ->endWith(function (InstallCommand $installCommand) {
                        $installCommand->info("Get ready to breathe easy! Our package has just saved you from a day's worth of headaches and hassle.");
                    });
            });
    }

    public function register()
    {
        Route::bind('post', function ($value) {
            return \FireFly\FilamentBlog\Models\Post::where('slug', $value)->published()->firstOrFail();
        });

        $this->app->register(EventServiceProvider::class);

        $this->app->singleton('seometa', function ($app) {
            return new SEOMeta(new Config($app->config->get('filamentblog.seo.meta')));
        });

        return parent::register(); // TODO: Change the autogenerated stub
    }
}
